# Generated by Django 6.0 on 2025-12-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(help_text='Start year, e.g., 2005', max_length=4)),
                ('end_year', models.CharField(help_text='End year, e.g., 2008', max_length=4)),
                ('degree', models.CharField(help_text='Degree name, e.g., Bachelor of Science', max_length=100)),
                ('university', models.CharField(help_text='Enter the name of the university', max_length=100)),
                ('description', models.TextField(help_text='Add a description of your education')),
                ('about_me', models.ForeignKey(help_text='Select the profile this education belongs to', on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(help_text='Start year, e.g., 2018', max_length=4)),
                ('end_year', models.CharField(help_text='End year, e.g., 2021', max_length=4)),
                ('position', models.CharField(help_text='Job position, e.g., Software Engineer', max_length=100)),
                ('company', models.CharField(help_text='Company name', max_length=100)),
                ('description', models.TextField(help_text='Describe your responsibilities and achievements')),
                ('about_me', models.ForeignKey(help_text='Select the profile this experience belongs to', on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
    ]
