# Generated by Django 6.0 on 2025-12-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_eduacation_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter project title', max_length=100)),
                ('year', models.CharField(help_text='Enter project year, e.g., 2023', max_length=4)),
                ('client', models.CharField(help_text='Client name (optional)', max_length=100)),
                ('service', models.CharField(help_text='Type of service provided', max_length=100)),
                ('project_type', models.CharField(help_text='Project category/type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project', null=True)),
                ('slug', models.SlugField(help_text='Automatically generated slug from title', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Mark whether this project is active')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Project creation date')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image related to the project', upload_to='project/image')),
                ('project', models.ForeignKey(help_text='Select the project for this image', on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
