# Generated by Django 6.0 on 2025-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Foydalanuvchi ismi', max_length=255)),
                ('email', models.EmailField(help_text='Foydalanuvchi emaili', max_length=254)),
                ('subject', models.CharField(help_text='Xabar mavzusi', max_length=255)),
                ('message', models.TextField(help_text='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
