# Generated by Django 6.0 on 2025-12-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon'), ('address', 'Manzil')], help_text='Kontakt turi: email, telefon yoki manzil', max_length=20)),
                ('title', models.CharField(help_text='Masalan: Email, Telefon, Manzil', max_length=100)),
                ('line1', models.CharField(help_text='Birinchi qator', max_length=255)),
                ('line2', models.CharField(blank=True, help_text='Ikkinchi qator (ixtiyoriy)', max_length=255, null=True)),
                ('line3', models.CharField(blank=True, help_text='Uchinchi qator (ixtiyoriy)', max_length=255, null=True)),
            ],
        ),
    ]
