# Generated by Django 6.0 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('profile', 'Profile'), ('work_together', 'Work Together'), ('credentials', 'Credentials')], max_length=20)),
                ('bg_image', models.ImageField(upload_to='info_box/')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='info_box/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Font Awesome yoki Iconoir klassini yozing', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
