# Generated by Django 6.0 on 2025-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_infobox_alter_service_icon_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner main text', max_length=255)),
                ('featured_text', models.CharField(help_text='Text to highlight', max_length=255)),
                ('image', models.ImageField(help_text='Star image or icon', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoBox',
        ),
    ]
