# Generated by Django 6.0 on 2025-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_banner_delete_infobox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Raqam, masalan: 07 yoki +125', max_length=10)),
                ('title', models.CharField(help_text='Stat sarlavhasi, masalan: Yillik Tajriba', max_length=50)),
                ('description', models.CharField(help_text='Qo‘shimcha matn, masalan: Mijozlar butun dunyo bo‘ylab', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Faol bo‘lsin yoki yo‘q')),
            ],
            options={
                'verbose_name': 'Mijoz Statistikasi',
                'verbose_name_plural': 'Mijoz Statistikalari',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
