# Generated by Django 4.2.25 on 2025-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_aboutme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your profile image (optional)', null=True, upload_to='about_me/image'),
        ),
    ]
