# Generated by Django 4.2.25 on 2025-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_aboutme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image_name',
            field=models.CharField(default='port.jpg', help_text='Static images/portfolio papkasidagi rasm nomi', max_length=100),
        ),
    ]
