# Generated by Django 4.2.25 on 2025-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_aboutme_image_aboutme_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_name',
            field=models.CharField(default='default_blog.jpg', help_text='Static images/blog papkasidagi rasm nomi', max_length=100),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_name',
            field=models.CharField(default='default_project.jpg', help_text='Static images/project papkasidagi rasm nomi', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon'), ('address', 'Manzil')], help_text='Kontakt turi', max_length=20),
        ),
    ]
